### PR TITLE
Fix comparison logic for existing record

### LINKED ISSUE #4: Running for different subdomains deletes all but home
At the moment, if you run

`./netlify-ddns_linux_amd64 update --domain exmple.com --subdomain "home"`

The correct A types gets created:

```
Name: home.example.com
TTL: 3600 seconds
Type: A
Value: 111.222.333.4444
```

Running again:

`./netlify-ddns_linux_amd64 update --domain exmple.com --subdomain "test"`

Will result in home getting deleted, and having only:

```
Name: test.example.com
TTL: 3600 seconds
Type: A
Value: 111.222.333.444
```

### PR DESCRIPTION
**Pull request by amirhomayoun**
The value in records coming back is the IP address. The name is in the format "subdomain.domain".
This fixes #4.
I tested the fix, and can successfully update multiple sub-domains.

### CODE REVIEW

**Comment by oscartbeaumont** [comment]
I tested your changes and it is not working for me as you described in issue #4.
I ran the commands
```bash
go run ./cmd/ update --domain otbeaumont.me --subdomain home
go run ./cmd/ update --domain otbeaumont.me --subdomain test
```
I then check my DNS records and I only see `test.otbeaumont.me`. Sorry it took me so long to get around to this PR. I can fix the TravisCI errors but have I understood the issue correctly and then why isn't the fix working for me.
Thanks for your contribution.

**Comment by amirhomayoun** [comment]
Hey. Thanks for the tool! It's great, and has helped me a lot!
So, if you try the existing code, do you see the issue? Without my fix, only one subdomain will be updated. Just want to confirm we both see the problem. 
Can you try building a binary and running it? That's what I did and the binary is working fine. (Working on this was my first experience ever with go, so I might have done something wrong/weird!)

**Comment by oscartbeaumont** [comment]
With the latest releases from my repo, I do observe the issue. When I clone and run your code (I also tried building it) and test I do not see the issue go away. I use the following commands:
`bash
git clone https://github.com/amirhomayoun/netlify-dynamic-dns
cd netlify-dynamic-dns/
go run ./cmd/ update --domain otbeaumont.me --subdomain home
go run ./cmd/ update --domain otbeaumont.me --subdomain test
`
I then check my DNS records to find `test.otbeaumont.me`. The `home.otbeaumont.me` record was deleted which If I understand correctly is the bug. The desired action is for both to exist. Does your PR fix the issue still for you because for some reason it is not for me?

**Comment by oscartbeaumont** [comment]
Does your PR fix the issue still for you because for some reason it is not for me?

**Comment by oscartbeaumont** [comment]
I am going to close this PR as the fixes were not acting correctly in my environment last I tested. However, the new codebase has a much simpler logic, which should prevent these issues.
Thanks for the PR.

**Pull request closed without merging**
